name: GoldenDupe
version: '${version}'
api-version: '1.21'
authors: [Antritus, _Devourer]
description: GoldenDupe's new engine is here!
website: goldendupe.xyz

# The main plugin
main: xyz.goldendupe.GoldenDupe
# Makes sure the plugin is used by paper servers and not spigot servers
# Loads commands
bootstrapper: xyz.goldendupe.GoldenDupeBootstrap
# Loads the libraries for the plugin
loader: xyz.goldendupe.GoldenDupeLoader

dependencies:
  server:
    LuckPerms:
      load: BEFORE
      required: false
      join-classpath: true
