name: GoldenDupe
version: '${version}'
main: xyz.goldendupe.GoldenDupe
api-version: '1.20'
authors: [Antritus, _Devourer]
description: GoldenDupe's new engine is here. Powering 80% of GoldenDupe hopefully without lag.
website: goldendupe.xyz

dependencies:
  server:
    Vault:
      load: BEFORE
      required: false
      join-classpath: true
    LuckPerms:
      load: BEFORE
      required: false
      join-classpath: true
    Fluffy:
      load: BEFORE
      required: false
      join-classpath: true
