name: GoldenDupe
version: '${version}'
api-version: '1.20'
authors: [Antritus, _Devourer]
description: GoldenDupe's new engine is here. Powering 80% of GoldenDupe hopefully without lag.
website: goldendupe.xyz

# The main plugin
main: xyz.goldendupe.GoldenDupe
# Makes sure the plugin is used by paper servers and not spigot servers
bootstrapper: xyz.goldendupe.GoldenDupeBoostrap
# Loads the libraries for the plugin
loader: xyz.goldendupe.GoldenDupeLoader

dependencies:
  server:
    Vault:
      load: BEFORE
      required: false
      join-classpath: true
    LuckPerms:
      load: BEFORE
      required: false
      join-classpath: true
    Fluffy:
      load: BEFORE
      required: false
      join-classpath: true
    Unity:
      load: BEFORE
      required: true
      join-classpath: true
